// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.openschedule.domain;

import java.lang.String;

privileged aspect Label_Roo_JavaBean {
    
    public String Label.getName() {
        return this.name;
    }
    
    public void Label.setName(String name) {
        this.name = name;
    }
    
}
