// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.openschedule.domain;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.openschedule.domain.BlockCommentDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect BlockCommentIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BlockCommentIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BlockCommentIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: BlockCommentIntegrationTest: @Transactional;
    
    @Autowired
    private BlockCommentDataOnDemand BlockCommentIntegrationTest.dod;
    
    @Test
    public void BlockCommentIntegrationTest.testCountBlockComments() {
        org.junit.Assert.assertNotNull("Data on demand for 'BlockComment' failed to initialize correctly", dod.getRandomBlockComment());
        long count = org.openschedule.domain.BlockComment.countBlockComments();
        org.junit.Assert.assertTrue("Counter for 'BlockComment' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BlockCommentIntegrationTest.testFindBlockComment() {
        org.openschedule.domain.BlockComment obj = dod.getRandomBlockComment();
        org.junit.Assert.assertNotNull("Data on demand for 'BlockComment' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'BlockComment' failed to provide an identifier", id);
        obj = org.openschedule.domain.BlockComment.findBlockComment(id);
        org.junit.Assert.assertNotNull("Find method for 'BlockComment' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'BlockComment' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void BlockCommentIntegrationTest.testFindAllBlockComments() {
        org.junit.Assert.assertNotNull("Data on demand for 'BlockComment' failed to initialize correctly", dod.getRandomBlockComment());
        long count = org.openschedule.domain.BlockComment.countBlockComments();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'BlockComment', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.openschedule.domain.BlockComment> result = org.openschedule.domain.BlockComment.findAllBlockComments();
        org.junit.Assert.assertNotNull("Find all method for 'BlockComment' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'BlockComment' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BlockCommentIntegrationTest.testFindBlockCommentEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'BlockComment' failed to initialize correctly", dod.getRandomBlockComment());
        long count = org.openschedule.domain.BlockComment.countBlockComments();
        if (count > 20) count = 20;
        java.util.List<org.openschedule.domain.BlockComment> result = org.openschedule.domain.BlockComment.findBlockCommentEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'BlockComment' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'BlockComment' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BlockCommentIntegrationTest.testFlush() {
        org.openschedule.domain.BlockComment obj = dod.getRandomBlockComment();
        org.junit.Assert.assertNotNull("Data on demand for 'BlockComment' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'BlockComment' failed to provide an identifier", id);
        obj = org.openschedule.domain.BlockComment.findBlockComment(id);
        org.junit.Assert.assertNotNull("Find method for 'BlockComment' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyBlockComment(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'BlockComment' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BlockCommentIntegrationTest.testMerge() {
        org.openschedule.domain.BlockComment obj = dod.getRandomBlockComment();
        org.junit.Assert.assertNotNull("Data on demand for 'BlockComment' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'BlockComment' failed to provide an identifier", id);
        obj = org.openschedule.domain.BlockComment.findBlockComment(id);
        boolean modified =  dod.modifyBlockComment(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.openschedule.domain.BlockComment merged = (org.openschedule.domain.BlockComment) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'BlockComment' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BlockCommentIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'BlockComment' failed to initialize correctly", dod.getRandomBlockComment());
        org.openschedule.domain.BlockComment obj = dod.getNewTransientBlockComment(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'BlockComment' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'BlockComment' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'BlockComment' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void BlockCommentIntegrationTest.testRemove() {
        org.openschedule.domain.BlockComment obj = dod.getRandomBlockComment();
        org.junit.Assert.assertNotNull("Data on demand for 'BlockComment' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'BlockComment' failed to provide an identifier", id);
        obj = org.openschedule.domain.BlockComment.findBlockComment(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'BlockComment' with identifier '" + id + "'", org.openschedule.domain.BlockComment.findBlockComment(id));
    }
    
}
