// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.openschedule.domain;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect EventCommentIntegrationTest_Roo_Configurable {
    
    declare @type: EventCommentIntegrationTest: @Configurable;
    
}
