// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.openschedule.domain;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.openschedule.domain.SessionDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SessionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SessionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SessionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: SessionIntegrationTest: @Transactional;
    
    @Autowired
    private SessionDataOnDemand SessionIntegrationTest.dod;
    
    @Test
    public void SessionIntegrationTest.testCountSessions() {
        org.junit.Assert.assertNotNull("Data on demand for 'Session' failed to initialize correctly", dod.getRandomSession());
        long count = org.openschedule.domain.Session.countSessions();
        org.junit.Assert.assertTrue("Counter for 'Session' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SessionIntegrationTest.testFindSession() {
        org.openschedule.domain.Session obj = dod.getRandomSession();
        org.junit.Assert.assertNotNull("Data on demand for 'Session' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Session' failed to provide an identifier", id);
        obj = org.openschedule.domain.Session.findSession(id);
        org.junit.Assert.assertNotNull("Find method for 'Session' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Session' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SessionIntegrationTest.testFindAllSessions() {
        org.junit.Assert.assertNotNull("Data on demand for 'Session' failed to initialize correctly", dod.getRandomSession());
        long count = org.openschedule.domain.Session.countSessions();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Session', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.openschedule.domain.Session> result = org.openschedule.domain.Session.findAllSessions();
        org.junit.Assert.assertNotNull("Find all method for 'Session' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Session' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SessionIntegrationTest.testFindSessionEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Session' failed to initialize correctly", dod.getRandomSession());
        long count = org.openschedule.domain.Session.countSessions();
        if (count > 20) count = 20;
        java.util.List<org.openschedule.domain.Session> result = org.openschedule.domain.Session.findSessionEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Session' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Session' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SessionIntegrationTest.testFlush() {
        org.openschedule.domain.Session obj = dod.getRandomSession();
        org.junit.Assert.assertNotNull("Data on demand for 'Session' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Session' failed to provide an identifier", id);
        obj = org.openschedule.domain.Session.findSession(id);
        org.junit.Assert.assertNotNull("Find method for 'Session' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySession(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Session' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SessionIntegrationTest.testMerge() {
        org.openschedule.domain.Session obj = dod.getRandomSession();
        org.junit.Assert.assertNotNull("Data on demand for 'Session' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Session' failed to provide an identifier", id);
        obj = org.openschedule.domain.Session.findSession(id);
        boolean modified =  dod.modifySession(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.openschedule.domain.Session merged = (org.openschedule.domain.Session) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Session' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SessionIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Session' failed to initialize correctly", dod.getRandomSession());
        org.openschedule.domain.Session obj = dod.getNewTransientSession(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Session' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Session' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Session' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SessionIntegrationTest.testRemove() {
        org.openschedule.domain.Session obj = dod.getRandomSession();
        org.junit.Assert.assertNotNull("Data on demand for 'Session' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Session' failed to provide an identifier", id);
        obj = org.openschedule.domain.Session.findSession(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Session' with identifier '" + id + "'", org.openschedule.domain.Session.findSession(id));
    }
    
}
