// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.openschedule.domain;

import java.util.List;
import java.util.Random;
import org.openschedule.domain.Speaker;
import org.springframework.stereotype.Component;

privileged aspect SpeakerDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SpeakerDataOnDemand: @Component;
    
    private Random SpeakerDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Speaker> SpeakerDataOnDemand.data;
    
    public Speaker SpeakerDataOnDemand.getNewTransientSpeaker(int index) {
        org.openschedule.domain.Speaker obj = new org.openschedule.domain.Speaker();
        java.lang.String name = "name_" + index;
        if (name.length() > 255) {
            name  = name.substring(0, 255);
        }
        obj.setName(name);
        java.lang.String email = "email_" + index;
        if (email.length() > 255) {
            email  = email.substring(0, 255);
        }
        obj.setEmail(email);
        java.lang.String webSite = "webSite_" + index;
        if (webSite.length() > 255) {
            webSite  = webSite.substring(0, 255);
        }
        obj.setWebSite(webSite);
        java.lang.String phone = "phone_" + index;
        if (phone.length() > 255) {
            phone  = phone.substring(0, 255);
        }
        obj.setPhone(phone);
        java.lang.String bio = "bio_" + index;
        if (bio.length() > 2048) {
            bio  = bio.substring(0, 2048);
        }
        obj.setBio(bio);
        return obj;
    }
    
    public Speaker SpeakerDataOnDemand.getSpecificSpeaker(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Speaker obj = data.get(index);
        return Speaker.findSpeaker(obj.getId());
    }
    
    public Speaker SpeakerDataOnDemand.getRandomSpeaker() {
        init();
        Speaker obj = data.get(rnd.nextInt(data.size()));
        return Speaker.findSpeaker(obj.getId());
    }
    
    public boolean SpeakerDataOnDemand.modifySpeaker(Speaker obj) {
        return false;
    }
    
    public void SpeakerDataOnDemand.init() {
        data = org.openschedule.domain.Speaker.findSpeakerEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Speaker' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.openschedule.domain.Speaker>();
        for (int i = 0; i < 10; i++) {
            org.openschedule.domain.Speaker obj = getNewTransientSpeaker(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
