// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.openschedule.domain;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.openschedule.domain.AuthorityDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AuthorityIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AuthorityIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AuthorityIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: AuthorityIntegrationTest: @Transactional;
    
    @Autowired
    private AuthorityDataOnDemand AuthorityIntegrationTest.dod;
    
    @Test
    public void AuthorityIntegrationTest.testCountAuthoritys() {
        org.junit.Assert.assertNotNull("Data on demand for 'Authority' failed to initialize correctly", dod.getRandomAuthority());
        long count = org.openschedule.domain.Authority.countAuthoritys();
        org.junit.Assert.assertTrue("Counter for 'Authority' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AuthorityIntegrationTest.testFindAuthority() {
        org.openschedule.domain.Authority obj = dod.getRandomAuthority();
        org.junit.Assert.assertNotNull("Data on demand for 'Authority' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Authority' failed to provide an identifier", id);
        obj = org.openschedule.domain.Authority.findAuthority(id);
        org.junit.Assert.assertNotNull("Find method for 'Authority' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Authority' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AuthorityIntegrationTest.testFindAllAuthoritys() {
        org.junit.Assert.assertNotNull("Data on demand for 'Authority' failed to initialize correctly", dod.getRandomAuthority());
        long count = org.openschedule.domain.Authority.countAuthoritys();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Authority', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.openschedule.domain.Authority> result = org.openschedule.domain.Authority.findAllAuthoritys();
        org.junit.Assert.assertNotNull("Find all method for 'Authority' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Authority' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AuthorityIntegrationTest.testFindAuthorityEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Authority' failed to initialize correctly", dod.getRandomAuthority());
        long count = org.openschedule.domain.Authority.countAuthoritys();
        if (count > 20) count = 20;
        java.util.List<org.openschedule.domain.Authority> result = org.openschedule.domain.Authority.findAuthorityEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Authority' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Authority' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AuthorityIntegrationTest.testFlush() {
        org.openschedule.domain.Authority obj = dod.getRandomAuthority();
        org.junit.Assert.assertNotNull("Data on demand for 'Authority' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Authority' failed to provide an identifier", id);
        obj = org.openschedule.domain.Authority.findAuthority(id);
        org.junit.Assert.assertNotNull("Find method for 'Authority' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAuthority(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Authority' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AuthorityIntegrationTest.testMerge() {
        org.openschedule.domain.Authority obj = dod.getRandomAuthority();
        org.junit.Assert.assertNotNull("Data on demand for 'Authority' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Authority' failed to provide an identifier", id);
        obj = org.openschedule.domain.Authority.findAuthority(id);
        boolean modified =  dod.modifyAuthority(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.openschedule.domain.Authority merged = (org.openschedule.domain.Authority) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Authority' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AuthorityIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Authority' failed to initialize correctly", dod.getRandomAuthority());
        org.openschedule.domain.Authority obj = dod.getNewTransientAuthority(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Authority' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Authority' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Authority' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AuthorityIntegrationTest.testRemove() {
        org.openschedule.domain.Authority obj = dod.getRandomAuthority();
        org.junit.Assert.assertNotNull("Data on demand for 'Authority' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Authority' failed to provide an identifier", id);
        obj = org.openschedule.domain.Authority.findAuthority(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Authority' with identifier '" + id + "'", org.openschedule.domain.Authority.findAuthority(id));
    }
    
}
