// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.openschedule.domain;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.openschedule.domain.BlockDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect BlockIntegrationTest_Roo_IntegrationTest {
    
    declare @type: BlockIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: BlockIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: BlockIntegrationTest: @Transactional;
    
    @Autowired
    private BlockDataOnDemand BlockIntegrationTest.dod;
    
    @Test
    public void BlockIntegrationTest.testCountBlocks() {
        org.junit.Assert.assertNotNull("Data on demand for 'Block' failed to initialize correctly", dod.getRandomBlock());
        long count = org.openschedule.domain.Block.countBlocks();
        org.junit.Assert.assertTrue("Counter for 'Block' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void BlockIntegrationTest.testFindBlock() {
        org.openschedule.domain.Block obj = dod.getRandomBlock();
        org.junit.Assert.assertNotNull("Data on demand for 'Block' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Block' failed to provide an identifier", id);
        obj = org.openschedule.domain.Block.findBlock(id);
        org.junit.Assert.assertNotNull("Find method for 'Block' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Block' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void BlockIntegrationTest.testFindAllBlocks() {
        org.junit.Assert.assertNotNull("Data on demand for 'Block' failed to initialize correctly", dod.getRandomBlock());
        long count = org.openschedule.domain.Block.countBlocks();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Block', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.openschedule.domain.Block> result = org.openschedule.domain.Block.findAllBlocks();
        org.junit.Assert.assertNotNull("Find all method for 'Block' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Block' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void BlockIntegrationTest.testFindBlockEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Block' failed to initialize correctly", dod.getRandomBlock());
        long count = org.openschedule.domain.Block.countBlocks();
        if (count > 20) count = 20;
        java.util.List<org.openschedule.domain.Block> result = org.openschedule.domain.Block.findBlockEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Block' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Block' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void BlockIntegrationTest.testFlush() {
        org.openschedule.domain.Block obj = dod.getRandomBlock();
        org.junit.Assert.assertNotNull("Data on demand for 'Block' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Block' failed to provide an identifier", id);
        obj = org.openschedule.domain.Block.findBlock(id);
        org.junit.Assert.assertNotNull("Find method for 'Block' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyBlock(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Block' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BlockIntegrationTest.testMerge() {
        org.openschedule.domain.Block obj = dod.getRandomBlock();
        org.junit.Assert.assertNotNull("Data on demand for 'Block' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Block' failed to provide an identifier", id);
        obj = org.openschedule.domain.Block.findBlock(id);
        boolean modified =  dod.modifyBlock(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.openschedule.domain.Block merged = (org.openschedule.domain.Block) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Block' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void BlockIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Block' failed to initialize correctly", dod.getRandomBlock());
        org.openschedule.domain.Block obj = dod.getNewTransientBlock(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Block' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Block' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Block' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void BlockIntegrationTest.testRemove() {
        org.openschedule.domain.Block obj = dod.getRandomBlock();
        org.junit.Assert.assertNotNull("Data on demand for 'Block' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Block' failed to provide an identifier", id);
        obj = org.openschedule.domain.Block.findBlock(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Block' with identifier '" + id + "'", org.openschedule.domain.Block.findBlock(id));
    }
    
}
