// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.openschedule.domain;

import java.util.List;
import java.util.Random;
import org.openschedule.domain.EventComment;
import org.springframework.stereotype.Component;

privileged aspect EventCommentDataOnDemand_Roo_DataOnDemand {
    
    declare @type: EventCommentDataOnDemand: @Component;
    
    private Random EventCommentDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<EventComment> EventCommentDataOnDemand.data;
    
    public EventComment EventCommentDataOnDemand.getNewTransientEventComment(int index) {
        org.openschedule.domain.EventComment obj = new org.openschedule.domain.EventComment();
        obj.setName(null);
        obj.setEmail(null);
        java.lang.String comment = "comment_" + index;
        if (comment.length() > 1024) {
            comment  = comment.substring(0, 1024);
        }
        obj.setComment(comment);
        return obj;
    }
    
    public EventComment EventCommentDataOnDemand.getSpecificEventComment(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        EventComment obj = data.get(index);
        return EventComment.findEventComment(obj.getId());
    }
    
    public EventComment EventCommentDataOnDemand.getRandomEventComment() {
        init();
        EventComment obj = data.get(rnd.nextInt(data.size()));
        return EventComment.findEventComment(obj.getId());
    }
    
    public boolean EventCommentDataOnDemand.modifyEventComment(EventComment obj) {
        return false;
    }
    
    public void EventCommentDataOnDemand.init() {
        data = org.openschedule.domain.EventComment.findEventCommentEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'EventComment' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.openschedule.domain.EventComment>();
        for (int i = 0; i < 10; i++) {
            org.openschedule.domain.EventComment obj = getNewTransientEventComment(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
