// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.openschedule.domain;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.openschedule.domain.SponsorDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SponsorIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SponsorIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SponsorIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: SponsorIntegrationTest: @Transactional;
    
    @Autowired
    private SponsorDataOnDemand SponsorIntegrationTest.dod;
    
    @Test
    public void SponsorIntegrationTest.testCountSponsors() {
        org.junit.Assert.assertNotNull("Data on demand for 'Sponsor' failed to initialize correctly", dod.getRandomSponsor());
        long count = org.openschedule.domain.Sponsor.countSponsors();
        org.junit.Assert.assertTrue("Counter for 'Sponsor' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SponsorIntegrationTest.testFindSponsor() {
        org.openschedule.domain.Sponsor obj = dod.getRandomSponsor();
        org.junit.Assert.assertNotNull("Data on demand for 'Sponsor' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Sponsor' failed to provide an identifier", id);
        obj = org.openschedule.domain.Sponsor.findSponsor(id);
        org.junit.Assert.assertNotNull("Find method for 'Sponsor' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Sponsor' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SponsorIntegrationTest.testFindAllSponsors() {
        org.junit.Assert.assertNotNull("Data on demand for 'Sponsor' failed to initialize correctly", dod.getRandomSponsor());
        long count = org.openschedule.domain.Sponsor.countSponsors();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Sponsor', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.openschedule.domain.Sponsor> result = org.openschedule.domain.Sponsor.findAllSponsors();
        org.junit.Assert.assertNotNull("Find all method for 'Sponsor' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Sponsor' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SponsorIntegrationTest.testFindSponsorEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Sponsor' failed to initialize correctly", dod.getRandomSponsor());
        long count = org.openschedule.domain.Sponsor.countSponsors();
        if (count > 20) count = 20;
        java.util.List<org.openschedule.domain.Sponsor> result = org.openschedule.domain.Sponsor.findSponsorEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Sponsor' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Sponsor' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SponsorIntegrationTest.testFlush() {
        org.openschedule.domain.Sponsor obj = dod.getRandomSponsor();
        org.junit.Assert.assertNotNull("Data on demand for 'Sponsor' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Sponsor' failed to provide an identifier", id);
        obj = org.openschedule.domain.Sponsor.findSponsor(id);
        org.junit.Assert.assertNotNull("Find method for 'Sponsor' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySponsor(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Sponsor' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SponsorIntegrationTest.testMerge() {
        org.openschedule.domain.Sponsor obj = dod.getRandomSponsor();
        org.junit.Assert.assertNotNull("Data on demand for 'Sponsor' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Sponsor' failed to provide an identifier", id);
        obj = org.openschedule.domain.Sponsor.findSponsor(id);
        boolean modified =  dod.modifySponsor(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.openschedule.domain.Sponsor merged = (org.openschedule.domain.Sponsor) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Sponsor' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SponsorIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Sponsor' failed to initialize correctly", dod.getRandomSponsor());
        org.openschedule.domain.Sponsor obj = dod.getNewTransientSponsor(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Sponsor' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Sponsor' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Sponsor' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SponsorIntegrationTest.testRemove() {
        org.openschedule.domain.Sponsor obj = dod.getRandomSponsor();
        org.junit.Assert.assertNotNull("Data on demand for 'Sponsor' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Sponsor' failed to provide an identifier", id);
        obj = org.openschedule.domain.Sponsor.findSponsor(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Sponsor' with identifier '" + id + "'", org.openschedule.domain.Sponsor.findSponsor(id));
    }
    
}
