// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.openschedule.domain;

import java.util.List;
import java.util.Random;
import org.openschedule.domain.Venue;
import org.springframework.stereotype.Component;

privileged aspect VenueDataOnDemand_Roo_DataOnDemand {
    
    declare @type: VenueDataOnDemand: @Component;
    
    private Random VenueDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Venue> VenueDataOnDemand.data;
    
    public Venue VenueDataOnDemand.getNewTransientVenue(int index) {
        org.openschedule.domain.Venue obj = new org.openschedule.domain.Venue();
        java.lang.String name = "name_" + index;
        if (name.length() > 255) {
            name  = name.substring(0, 255);
        }
        obj.setName(name);
        obj.setAddressOne(null);
        obj.setAddressTwo(null);
        obj.setCity(null);
        obj.setState(null);
        obj.setZip(null);
        obj.setWebSite(null);
        obj.setEmail(null);
        obj.setPhone(null);
        return obj;
    }
    
    public Venue VenueDataOnDemand.getSpecificVenue(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Venue obj = data.get(index);
        return Venue.findVenue(obj.getId());
    }
    
    public Venue VenueDataOnDemand.getRandomVenue() {
        init();
        Venue obj = data.get(rnd.nextInt(data.size()));
        return Venue.findVenue(obj.getId());
    }
    
    public boolean VenueDataOnDemand.modifyVenue(Venue obj) {
        return false;
    }
    
    public void VenueDataOnDemand.init() {
        data = org.openschedule.domain.Venue.findVenueEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Venue' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<org.openschedule.domain.Venue>();
        for (int i = 0; i < 10; i++) {
            org.openschedule.domain.Venue obj = getNewTransientVenue(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
