// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.openschedule.domain;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.openschedule.domain.VenueDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect VenueIntegrationTest_Roo_IntegrationTest {
    
    declare @type: VenueIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: VenueIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: VenueIntegrationTest: @Transactional;
    
    @Autowired
    private VenueDataOnDemand VenueIntegrationTest.dod;
    
    @Test
    public void VenueIntegrationTest.testCountVenues() {
        org.junit.Assert.assertNotNull("Data on demand for 'Venue' failed to initialize correctly", dod.getRandomVenue());
        long count = org.openschedule.domain.Venue.countVenues();
        org.junit.Assert.assertTrue("Counter for 'Venue' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void VenueIntegrationTest.testFindVenue() {
        org.openschedule.domain.Venue obj = dod.getRandomVenue();
        org.junit.Assert.assertNotNull("Data on demand for 'Venue' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Venue' failed to provide an identifier", id);
        obj = org.openschedule.domain.Venue.findVenue(id);
        org.junit.Assert.assertNotNull("Find method for 'Venue' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Venue' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void VenueIntegrationTest.testFindAllVenues() {
        org.junit.Assert.assertNotNull("Data on demand for 'Venue' failed to initialize correctly", dod.getRandomVenue());
        long count = org.openschedule.domain.Venue.countVenues();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Venue', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.openschedule.domain.Venue> result = org.openschedule.domain.Venue.findAllVenues();
        org.junit.Assert.assertNotNull("Find all method for 'Venue' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Venue' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void VenueIntegrationTest.testFindVenueEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Venue' failed to initialize correctly", dod.getRandomVenue());
        long count = org.openschedule.domain.Venue.countVenues();
        if (count > 20) count = 20;
        java.util.List<org.openschedule.domain.Venue> result = org.openschedule.domain.Venue.findVenueEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Venue' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Venue' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void VenueIntegrationTest.testFlush() {
        org.openschedule.domain.Venue obj = dod.getRandomVenue();
        org.junit.Assert.assertNotNull("Data on demand for 'Venue' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Venue' failed to provide an identifier", id);
        obj = org.openschedule.domain.Venue.findVenue(id);
        org.junit.Assert.assertNotNull("Find method for 'Venue' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyVenue(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Venue' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void VenueIntegrationTest.testMerge() {
        org.openschedule.domain.Venue obj = dod.getRandomVenue();
        org.junit.Assert.assertNotNull("Data on demand for 'Venue' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Venue' failed to provide an identifier", id);
        obj = org.openschedule.domain.Venue.findVenue(id);
        boolean modified =  dod.modifyVenue(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.openschedule.domain.Venue merged = (org.openschedule.domain.Venue) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Venue' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void VenueIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Venue' failed to initialize correctly", dod.getRandomVenue());
        org.openschedule.domain.Venue obj = dod.getNewTransientVenue(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Venue' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Venue' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Venue' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void VenueIntegrationTest.testRemove() {
        org.openschedule.domain.Venue obj = dod.getRandomVenue();
        org.junit.Assert.assertNotNull("Data on demand for 'Venue' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Venue' failed to provide an identifier", id);
        obj = org.openschedule.domain.Venue.findVenue(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Venue' with identifier '" + id + "'", org.openschedule.domain.Venue.findVenue(id));
    }
    
}
