// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.openschedule.domain;

import java.io.Serializable;

privileged aspect BlockComment_Roo_Serializable {
    
    declare parents: BlockComment implements Serializable;
    
    private static final long BlockComment.serialVersionUID = 1L;
    
}
