// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.openschedule.domain;

import java.io.Serializable;

privileged aspect Session_Roo_Serializable {
    
    declare parents: Session implements Serializable;
    
    private static final long Session.serialVersionUID = 1L;
    
}
